Task4598 refactor vuetify alerts docs
jdi-docs/jdi-light pull request #1318
Opened 2023-01-11 14:20 UTC by Liliya-web

2023-01-13 12:46 UTC, MayaElf requested changes

2023-01-16 10:48 UTC, MayaElf approved these changes

2023-01-17 17:56 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +</template>
Please, change according to Vladimir's comments:
in a documentation near highlighted comment please also emphasize a Selenium locator findby 
![image](https://user-images.githubusercontent.com/55189259/212975403-347b94e2-445c-4b2b-96ba-2b5e4f8339fa.png)

2023-02-20 10:14 UTC, annav00 commented
Closed due to having a more recent PR with new updates (https://github.com/jdi-docs/jdi-light/pull/1343)

2023-02-20 10:14 UTC, closed without merging