Task4599 refactor vuetify aspect ratios docs
jdi-docs/jdi-light pull request #1319
Opened 2023-01-11 15:21 UTC by Liliya-web

2023-01-13 12:11 UTC, MayaElf requested changes

2023-01-13 12:11 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +For examples of usage see: [JDI Vuetify Chip tests](https://github.com/jdi-testing/jdi-light/blob/vuetify-develop/jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/common/AspectRatio
Hi :) Why is reference to Chip tests if the link is to AspectRatioTests? Please, clarify :)

2023-01-13 12:16 UTC, MayaElf requested changes

2023-01-13 12:16 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +### 5.39 Aspect Ratios
Sorry, failed to find this poin "7.	Element code (with reference to framework version - IMPORTANT!)" Could you please, clarify :)

2023-01-16 10:51 UTC, MayaElf approved these changes

2023-01-17 17:55 UTC, MayaElf requested changes

2023-01-17 17:55 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +```
Please, change according to Vladimir's comments:
in a documentation near highlighted comment please also emphasize a Selenium locator findby 

![image](https://user-images.githubusercontent.com/55189259/212975164-d661b64c-76cf-4de9-b8db-d8be1582451a.png)

2023-02-20 10:06 UTC, MayaElf approved these changes

2023-02-20 10:18 UTC, vklonin approved these changes

2023-02-20 10:19 UTC, merged