Task 4650: Rework Rating documentation
jdi-docs/jdi-light pull request #1330
Opened 2023-01-18 07:10 UTC by sergei820

2023-01-18 12:12 UTC, MayaElf requested changes

2023-01-19 07:28 UTC, sergei820 commented on source/includes/documentation/_vue_js_elements.md
> +| **getRatingButtons()**            | Get count buttons                         | int           |
Fixed. Thanks a lot!

2023-01-20 11:05 UTC, MayaElf approved these changes

2023-01-20 14:02 UTC, vklonin approved these changes

2023-01-20 14:02 UTC, merged