Task4597 - Refactor vuetify Overlay docs
jdi-docs/jdi-light pull request #1333
Opened 2023-01-23 15:22 UTC by MrShmiTT

The overlay chapter is refactored.

2023-01-23 15:45 UTC, MayaElf requested changes

2023-01-23 15:45 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +| **has()**                 | Returns object for work with assertions  | TooltipAssert |
Why Tooltip? :)

2023-01-23 15:45 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +| **is()**                  | Returns object for work with assertions  | TooltipAssert |
Why Tooltip? :)

2023-01-23 15:58 UTC, MrShmiTT commented on source/includes/documentation/_vue_js_elements.md
> +| **has()**                 | Returns object for work with assertions  | TooltipAssert |
Missprint :)
Fixed

2023-01-23 15:58 UTC, MrShmiTT commented on source/includes/documentation/_vue_js_elements.md
> +| **is()**                  | Returns object for work with assertions  | TooltipAssert |
Missprint :)
Fixed

2023-01-24 09:33 UTC, MayaElf approved these changes

2023-01-24 13:01 UTC, vklonin approved these changes

2023-01-24 13:01 UTC, merged