4624 documentation for vuetify element tables
jdi-docs/jdi-light pull request #1353
Opened 2023-02-27 14:10 UTC by OlgaPoddubnaia

2023-02-28 17:52 UTC, MayaElf requested changes

2023-02-28 17:52 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**has()/is()** | Returns Assert class                                                    | DataTableAssert
может быть, все ассерты тогда объединить в одной таблице? та, которая ниже? чтобы вместе логично

2023-02-28 17:52 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**has()/is()** | Returns Data Iterator Assert class            | DataIteratorAssert
может быть, ассерты все вместе? :)

2023-03-01 11:07 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +```
подрезала. оставила только первый элемент; далее с  <tr>  <...></tr>

2023-03-01 11:15 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
>  **hasFixedHeight()** | Shows that table has fixed height | boolean
конечно, на заметила сразу, чтов ысота тоже override;
удалила **has()/is()**, **height()**

2023-03-01 11:36 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +                        d="M13,20H11V8L5.5,13.5L4.08,12.08L12,4.16L19.92,12.08L18.5,13.5L13,8V20Z"></path></svg></span>
оставила 2 первых columnheader тк они разные и далее <...>

2023-03-01 11:44 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +**has()/is()** | Returns Assert class                                                    | DataTableAssert
удалила **has()/is()** тк они override  и атм нет внутри чего-то принципально отличающегося

2023-03-01 11:52 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +**has()/is()** | Returns Data Iterator Assert class            | DataIteratorAssert
удалила has()/is() тк они override и атм нет внутри чего-то принципально отличающегося

2023-03-06 15:57 UTC, MayaElf requested changes

2023-03-06 15:57 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
>  **isLight()** | Shows that table has light theme | boolean
dark и light, по идее, должны тянуться из интерфейса theme. или здесь какая-то особенная реализация? :)

2023-03-06 15:57 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**light()** | Assert that Simple Table is light theme
ассерты тоже должны тянуться из интерфейса theme :) или опять же какая-то специфическая реализация здесь? :)

2023-03-06 15:57 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +
height должна тянуться из интерфейса measurement, здесь специфическая реализация? :)

2023-03-06 15:57 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +
если есть интерфейс IsLoading, методы должны "тянуться" из него. Почему тогда есть отдельный метод isLoading(), см.выше список методов :)

2023-03-06 15:57 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**loading()** | Assert that Data Table group has size
то же, что см.выше. при наличии интерфейса IsLoading почему отдельные методы? :)

2023-03-07 10:02 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +**light()** | Assert that Simple Table is light theme
в HasTheme есть только один метод - theme(). в ThemeAssert есть методы на ligh и dark. Может нужно удалить методы тогда из SimpleTableAssert, SimpleTable методы на dark и light. предлагаю обсудить на колле

2023-03-07 10:02 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
>  **isLight()** | Shows that table has light theme | boolean
в HasTheme есть только один метод - theme(). в ThemeAssert есть методы на light и dark. Может нужно удалить методы тогда из SimpleTableAssert, SimpleTable методы на dark и light. предлагаю обсудить на колле

2023-03-07 10:09 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +
удалила) забыла убрать

2023-03-07 10:21 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +
в IsLoading элемент ищется таким образом core().attr("class").contains("-loading"). тут же ищется с помощью селектора div[role='progressbar']

2023-03-07 10:49 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +**loading()** | Assert that Data Table group has size
вотв  методе loading ничего нового нет. я бы его удалила из DataTableAssert.java ; удалила из таблицы здесь

2023-03-07 12:01 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
>  **isLight()** | Shows that table has light theme | boolean
сорри, это и имела ввиду))) всегда пишу только базовый интерфейс, дальше все равно от него все пляшет. я посмотрела тесты, молодой человек 09 01 23 по сути внутри SimpleTableAssert продублировал интерфейсные ассерты. А по сути тест работает с интерфейсными ассертами без проблем, вот так тогда будет выглядеть `@Test(description = "Test checks that table has dark or light theme")
    public static void themeSimpleTableTests() {
        darkTable.is().darkTheme();
        denseTable.show();
        denseTable.is().dense();
        denseTable.is().lightTheme();`
Да, давайте обсудим на коле, что с таким делать :)

2023-03-07 12:02 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**light()** | Assert that Simple Table is light theme
да, см. выше :)

2023-03-07 12:04 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +
а тогда вопрос, где-то мы используем в коде хоть что-то, что относится к интерфейсу IsLoading? Если здесь интерфейс не исп-ся, нужно убрать его из списка со строки 2615 :)

2023-03-09 15:33 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
>  **isLight()** | Shows that table has light theme | boolean
[PR](https://github.com/jdi-testing/jdi-light/pull/4799) related to those changes

2023-03-09 15:33 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +**light()** | Assert that Simple Table is light theme
[PR](https://github.com/jdi-testing/jdi-light/pull/4799) related to those changes

2023-03-10 16:58 UTC, MayaElf approved these changes

2023-03-23 14:42 UTC, OlgaPoddubnaia commented
@vklonin please look into this PR. Related [PR](https://github.com/jdi-docs/jdi-light/pull/1353) is merged

2023-03-24 08:55 UTC, merged