updated doc for Banner
jdi-docs/jdi-light pull request #1354
Opened 2023-02-28 15:06 UTC by OlgaPoddubnaia

2023-02-28 17:58 UTC, MayaElf requested changes

2023-02-28 17:58 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +@Test
all tests should have description :)

2023-03-01 10:56 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +@Test
added description

2023-03-02 09:04 UTC, vklonin approved these changes

2023-03-02 09:04 UTC, merged