4652 documentation for vuetify element skeleton loader
jdi-docs/jdi-light pull request #1363
Opened 2023-03-10 16:40 UTC by OlgaPoddubnaia

2023-03-10 16:54 UTC, MayaElf requested changes

2023-03-10 16:54 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +public void darkSkeletonLoaderTest() {
как предложение :) при расширении функционала теста менять тогда описание) а то в описании только про тему, а функционал проверяется гораздо больший :)

2023-03-13 16:43 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +public void darkSkeletonLoaderTest() {
поменяла на Check if dark skeleton loader looks as expected and is not boilerplate

2023-03-14 11:05 UTC, MayaElf approved these changes

2023-03-14 12:02 UTC, vklonin approved these changes

2023-03-14 12:02 UTC, merged