4625 documentation for vuetify element timelines
jdi-docs/jdi-light pull request #1368
Opened 2023-03-16 10:28 UTC by OlgaPoddubnaia

2023-03-17 13:05 UTC, MayaElf requested changes

2023-03-17 13:05 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +  class="v-timeline-item__inner-dot info"></div></div></div></div></span></div>
что-то с форматированием(((

2023-03-17 13:05 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
>  element by using generic. **That classes must implement `ICoreElement` interface**.
эта информация нужна здесь? не очень понятно, если честно)

2023-03-20 08:57 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +    //@FindBy(css = "#AdvancedTimeline .v-timeline")
убрала ТАВ перед //@FindBy

2023-03-20 09:17 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +  class="v-timeline-item__inner-dot info"></div></div></div></div></span></div>
поправила

2023-03-20 09:18 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
>  element by using generic. **That classes must implement `ICoreElement` interface**.
удалила "Also, you can specify classes for `body` as `T` and for `divider` as `U` in your 
element by using generic. **That classes must implement `ICoreElement` interface**."

2023-03-20 10:42 UTC, MayaElf approved these changes

2023-03-20 10:47 UTC, merged