4633 documentation for vuetify element color picker
jdi-docs/jdi-light pull request #1373
Opened 2023-03-22 13:45 UTC by OlgaPoddubnaia

2023-03-22 18:45 UTC, MayaElf requested changes

2023-03-22 18:45 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +
interfaces? :)

2023-03-23 15:03 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +
added interfaces

2023-03-24 08:57 UTC, MayaElf approved these changes

2023-03-24 08:59 UTC, merged