4636 documentation for vuetify element date picker
jdi-docs/jdi-light pull request #1376
Opened 2023-03-24 14:17 UTC by OlgaPoddubnaia

2023-03-24 14:30 UTC, MayaElf requested changes

2023-03-24 14:30 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +  root = "#OrientationDatePicker .v-picker")
специально не в одну строку? :)

2023-03-24 14:30 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
>  It is **necessary** to specify **the root** of an element. Also, if you work with expandable date pickers (such as active pickers, dialog and menu pickers etc), you have to define **expandedRoot**. T
проверь эту фразу, пож-та, идет отсылка на This is the root of element а потом идет просто html. чтобы путаницы не было:)

2023-03-24 14:49 UTC, OlgaPoddubnaia commented on source/includes/documentation/_vue_js_elements.md
> +  root = "#OrientationDatePicker .v-picker")
переместила)

2023-03-27 07:41 UTC, MayaElf approved these changes

2023-03-27 07:51 UTC, vklonin approved these changes

2023-03-27 07:51 UTC, merged