Updated documentation for Vuetify element: RangeSlider
jdi-docs/jdi-light pull request #1380
Opened 2023-03-31 15:17 UTC by prudei-core

2023-04-03 11:58 UTC, MayaElf requested changes

2023-04-03 11:58 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +The `v-slider` component is a better visualization of the number input.
should be 'v-range-slider' not to create mess. see API https://v2.vuetifyjs.com/en/api/v-range-slider/

2023-04-04 11:26 UTC, MayaElf approved these changes

2023-04-04 12:01 UTC, vklonin approved these changes

2023-04-04 12:01 UTC, merged