Updated documentation for Vuetify element: panels
jdi-docs/jdi-light pull request #1382
Opened 2023-04-03 15:30 UTC by lyalchenko1995

2023-04-03 18:22 UTC, MayaElf requested changes

2023-04-03 18:22 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
>  ExpansionPanels is a list of ExpansionPanel.
Maybe to put this phrase at the end of description?:)

2023-04-03 18:22 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
here we also put assert methods ExpansionPanelAssert and ExpansionPanelsAssert

2023-04-04 07:56 UTC, MayaElf requested changes

2023-04-04 07:56 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +
panelS asserts also should be here :)

2023-04-04 08:04 UTC, lyalchenko1995 commented on source/includes/documentation/_vue_js_elements.md
> +
They are above

2023-04-04 08:06 UTC, MayaElf approved these changes

2023-04-04 08:36 UTC, vklonin approved these changes

2023-04-04 08:36 UTC, merged