Task4623 documentation for vuetify element stepper
jdi-docs/jdi-light pull request #1384
Opened 2023-04-05 09:19 UTC by lyalchenko1995

2023-04-05 10:02 UTC, MayaElf requested changes

2023-04-05 10:02 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**steps()** | Returns list of steps for stepper | List<Step>
List<Step> здесь нужно экранировать, иначе остается только List при выводе

2023-04-05 10:39 UTC, lyalchenko1995 commented on source/includes/documentation/_vue_js_elements.md
> +
Done

2023-04-05 10:39 UTC, lyalchenko1995 commented on source/includes/documentation/_vue_js_elements.md
> +**getStep** | Returns step by index | Step
Done

2023-04-05 10:39 UTC, lyalchenko1995 commented on source/includes/documentation/_vue_js_elements.md
> +
Done

2023-04-05 10:39 UTC, lyalchenko1995 commented on source/includes/documentation/_vue_js_elements.md
> +**steps()** | Returns list of steps for stepper | List<Step>
Done

2023-04-05 15:44 UTC, MayaElf approved these changes

2023-04-06 07:28 UTC, vklonin approved these changes

2023-04-06 07:28 UTC, merged