Added documentation for Vuetify element: OTP Input
jdi-docs/jdi-light pull request #1391
Opened 2023-04-10 14:14 UTC by prudei-core

2023-04-10 18:50 UTC, MayaElf requested changes

2023-04-10 18:50 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**inputs()** | Returns OtpInput inputs | List\<TextField>
should be arguments in this method

2023-04-10 18:50 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +```
скобку влево, пож-та, на общий уровень

2023-04-11 10:33 UTC, MayaElf approved these changes

2023-04-11 15:13 UTC, vklonin approved these changes

2023-04-11 15:13 UTC, merged