[WIP] 4626 - updated autocompletes documentation
jdi-docs/jdi-light pull request #1393
Opened 2023-04-11 13:56 UTC by FursovaKate

2023-04-12 11:44 UTC, MayaElf requested changes

2023-04-12 11:44 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +@Test(description = "Test checks appearance of autocompletes and their values")
перед тестом обязательно вот такой набор для элемента, который у тебя в тесте(см.любой элемент в доках)
 //@FindBy(css = "#ThreeLineList .v-list")
    @UI("#ThreeLineList .v-list")
    public static VuetifyList threeLineList;

2023-04-12 11:44 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +
здесь еще указываем имплеметированные интерфейсы

2023-04-12 11:44 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +
таблицу с ассертными методами тоже добавляем, она выглядит немного по-другому, всего два столбца, посмотри в недавних пиарах, пож-та :)

2023-04-12 11:44 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +  }
скобка влево на общий уровень :)

2023-04-12 11:44 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**select(List<String> values)** | Select values from expanded list   | void
нужно экранировать перед String иначе на выходе получается List values

2023-04-12 11:44 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**unselect(List<String> values)** | Unselect values from expanded list | void
экранировать

2023-04-12 11:44 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +**isSelected(List<String> values)** | Check if the values are selected   | boolean
экранировать

2023-04-12 11:44 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +
должна быть master ветка (вместо большого набора цифр:))

2023-04-13 08:14 UTC, MayaElf requested changes

2023-04-13 08:14 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> +@JAutocomplete(root = "//div[@id='style']/div[2]//div[2]/div[contains(@class, 'v-autocomplete')]",
перед каждым локатором еще должен быть //FindBy, посмотри в других, пож-та

2023-04-18 09:21 UTC, MayaElf approved these changes

2023-04-18 09:33 UTC, vklonin approved these changes

2023-04-18 09:33 UTC, merged