updated DatePickerMonths documentation
jdi-docs/jdi-light pull request #1396
Opened 2023-04-14 07:57 UTC by FursovaKate

2023-04-18 07:10 UTC, MayaElf requested changes

2023-04-18 07:10 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
>  - __Java__: _com.epam.jdi.light.vuetify.elements.complex.DatePickerMonth.java_
link to docs should be with v2

2023-04-18 07:10 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
> + ```
у нас была договоренность, что в длинных элементах повторяющиеся части можно заменять точками. а то более 150 строк на элементо это много :)

2023-04-18 07:10 UTC, MayaElf commented on source/includes/documentation/_vue_js_elements.md
>  For examples of usage see: [JDI Vuetify DatePickersMonth tests](https://github.com/jdi-testing/jdi-light/blob/vuetify-develop/jdi-light-vuetify-tests/src/test/java/io/github/epam/vuetify/tests/comple
мастер ветка должна быть

2023-04-19 08:14 UTC, MayaElf approved these changes

2023-04-19 09:20 UTC, vklonin approved these changes

2023-04-19 09:20 UTC, merged